config/routes.rb
Blog::Application.routes.draw do

  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.find(:all)
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.new(params[:post])
    post.save
    redirect_to :action => 'index'
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update_attributes(params[:post])
    redirect_to :action => 'index'
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to :action => 'index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>
<%= form_for @post do |f| %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %> <br />
    <%= f.text_area :body %>
  </p>
  <%= f.submit 'Save' %>
<% end %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <h2><%= link_to h(post.title), post %></h2>
  <p><%=h post.body %></h2>
<% end %>

app/views/posts/new.html.erb
<h2>New Post</h2>
<%= form_for @post do |f| %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %> <br />
    <%= f.text_area :body %>
  </p>
  <%= f.submit 'Save' %>
<% end %>

app/views/posts/show.html.erb
<h2><%=h @post.title %></h2>
<p><%=h @post.body %></p>

<p><%= link_to 'Edit', edit_post_path(@post) %></p>
<p><%= link_to 'List of Posts', posts_path %></p>
<p><%= link_to 'Destroy', post_path(@post), :method => :delete, :confirm => 'Are you sure?' %></p>